# Generated by Django 5.2 on 2025-09-19 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Profil administrateur', 'verbose_name_plural': 'Profils administrateurs'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Profil Client', 'verbose_name_plural': 'Profils Clients'},
        ),
        migrations.AlterModelOptions(
            name='employeprofile',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Profil Employé', 'verbose_name_plural': 'Profils Employés'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='matricule',
            field=models.CharField(help_text="Matricule unique identifiant l'administrateur.", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='nom',
            field=models.CharField(help_text="Nom de famille de l'administrateur.", max_length=100),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='prenom',
            field=models.CharField(help_text="Prénom de l'administrateur.", max_length=100),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(help_text='Utilisateur lié à ce profil administrateur.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='cle_chiffree',
            field=models.CharField(help_text='Clé chiffrée générée automatiquement', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='nom',
            field=models.CharField(help_text='Nom de famille du client', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='prenom',
            field=models.CharField(help_text='Prénom du client', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='telephone',
            field=models.CharField(help_text='Numéro de téléphone', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(help_text='Utilisateur associé à ce profil client', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='identifiant_telephone',
            field=models.CharField(help_text='Identifiant téléphonique professionnel', max_length=255),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='matricule',
            field=models.CharField(help_text="Numéro de matricule unique de l'employé", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='nom',
            field=models.CharField(help_text="Nom de famille de l'employé", max_length=100),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='prenom',
            field=models.CharField(help_text="Prénom de l'employé", max_length=100),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='user',
            field=models.OneToOneField(help_text='Utilisateur associé à ce profil employé', on_delete=django.db.models.deletion.CASCADE, related_name='employe_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text="Adresse email unique servant d'identifiant", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Indique si l'utilisateur est actif"),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text="Accès à l'interface d'administration Django"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('employe', 'Employé')], default='client', help_text="Rôle de l'utilisateur dans le système", max_length=10),
        ),
    ]
