# Generated by Django 5.2 on 2025-10-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0012_remove_ticket_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(help_text='Données encodées dans le QR code', max_length=255)),
                ('ticket', models.ForeignKey(help_text='Ticket associé à ce QR code', on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='api.ticket')),
            ],
        ),
    ]
