# Generated by Django 5.2 on 2025-10-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='data',
            field=models.BinaryField(help_text='Données encodées dans le QR code'),
        ),
    ]
