# Generated by Django 5.2 on 2025-10-08 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code_service', '0002_alter_qrcode_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='data',
            field=models.TextField(help_text='Données encodées dans le QR code'),
        ),
    ]
