# Generated by Django 5.2 on 2025-10-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_ticket_qr_code'),
        ('qr_code_service', '0003_qrcode_create_at_alter_qrcode_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='ticket',
            field=models.OneToOneField(help_text='Ticket associé à ce QR code', on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='api.ticket'),
        ),
    ]
