# Generated by Django 5.2 on 2025-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_epreuve_evenement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='epreuve',
            constraint=models.UniqueConstraint(fields=('libelle', 'discipline'), name='unique_epreuve_per_discipline'),
        ),
    ]
