# Generated by Django 5.2 on 2025-07-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_epreuve_unique_epreuve_per_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves', to='api.evenement'),
        ),
    ]
