# Generated by Django 5.2 on 2025-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_epreuve_evenement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='epreuve',
            name='unique_epreuve_per_discipline',
        ),
        migrations.AddField(
            model_name='epreuve',
            name='genre',
            field=models.CharField(default='mixte', max_length=100),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='tour',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='epreuve',
            constraint=models.UniqueConstraint(fields=('libelle', 'genre', 'discipline', 'evenement'), name='unique_epreuve_par_discipline_genre_et_evenement'),
        ),
    ]
