# Generated by Django 5.2 on 2025-09-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_epreuve_unique_epreuve_per_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='icone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
