# Generated by Django 5.2 on 2025-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_discipline_icone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='epreuve',
            name='unique_epreuve_par_discipline_genre_et_evenement',
        ),
        migrations.AddConstraint(
            model_name='epreuve',
            constraint=models.UniqueConstraint(fields=('libelle', 'genre', 'discipline', 'tour', 'evenement'), name='unique_epreuve_par_discipline_genre_tour_et_evenement'),
        ),
    ]
