# Generated by Django 5.2 on 2025-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_epreuve_unique_epreuve_par_discipline_genre_et_evenement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('nb_personne', models.IntegerField(default=0)),
                ('montant', models.FloatField(default=0.0)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='nb_place_restante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='nb_place_total',
            field=models.IntegerField(default=1000),
        ),
    ]
