# Generated by Django 5.2 on 2025-09-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_offre_evenement_nb_place_restante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['nom'], 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AlterModelOptions(
            name='epreuve',
            options={'ordering': ['discipline__nom', 'genre', 'libelle'], 'verbose_name': 'Épreuve', 'verbose_name_plural': 'Épreuves'},
        ),
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ['date', 'horraire'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterModelOptions(
            name='lieu',
            options={'ordering': ['nom'], 'verbose_name': 'Lieu', 'verbose_name_plural': 'Lieux'},
        ),
        migrations.AlterModelOptions(
            name='offre',
            options={'ordering': ['nb_personne', 'montant'], 'verbose_name': 'Offre', 'verbose_name_plural': 'Offres'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='icone',
            field=models.CharField(default='', help_text="Chemin ou nom de l'icône de la discipline", max_length=200),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='nom',
            field=models.CharField(help_text='Nom de la discipline sportive', max_length=100),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='discipline',
            field=models.ForeignKey(help_text='Discipline sportive associée', on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='api.discipline'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='evenement',
            field=models.ForeignKey(blank=True, help_text='Événement associé à cette épreuve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves', to='api.evenement'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='genre',
            field=models.CharField(default='mixte', help_text="Genre de l'épreuve (homme, femme, mixte)", max_length=100),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='libelle',
            field=models.CharField(help_text="Intitulé de l'épreuve", max_length=100),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='tour',
            field=models.CharField(default='', help_text="Tour de l'épreuve (finale, demi-finale, qualification, etc.)", max_length=100),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(help_text="Date de l'événement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.CharField(help_text="Description de l'événement", max_length=250),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='horraire',
            field=models.TimeField(help_text="Heure de début de l'événement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.ForeignKey(help_text="Lieu où se déroule l'événement", on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='api.lieu'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nb_place_restante',
            field=models.IntegerField(blank=True, help_text='Nombre de places encore disponibles', null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nb_place_total',
            field=models.IntegerField(default=1000, help_text='Nombre total de places disponibles'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='nom',
            field=models.CharField(help_text='Nom du lieu sportif', max_length=100),
        ),
        migrations.AlterField(
            model_name='offre',
            name='description',
            field=models.TextField(default='', help_text="Description détaillée de l'offre"),
        ),
        migrations.AlterField(
            model_name='offre',
            name='libelle',
            field=models.CharField(help_text="Nom de l'offre", max_length=100),
        ),
        migrations.AlterField(
            model_name='offre',
            name='montant',
            field=models.FloatField(default=0.0, help_text="Montant de l'offre en euros"),
        ),
        migrations.AlterField(
            model_name='offre',
            name='nb_personne',
            field=models.IntegerField(default=0, help_text="Nombre de personnes concernées par l'offre"),
        ),
    ]
