# Generated by Django 5.2 on 2025-09-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_discipline_options_alter_epreuve_options_and_more'),
        ('users', '0002_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('invalide ', 'Invalide')], default='valide', max_length=10)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientprofile')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evenement')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offre')),
            ],
            options={
                'ordering': ['-date_achat'],
            },
        ),
    ]
