# Generated by Django 5.2 on 2025-09-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code',
        ),
    ]
