name: Deploiement API en Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployer sur le serveur
    runs-on: ubuntu-latest

    steps:
      - name: etape 1 recupération du code
        uses: actions/checkout@v3

      - name: etape 2 connexion SSH au serveur
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: etape 3 Pull sur serveur
        run: |
          ssh -o StrictHostKeyChecking=no deploy@167.172.53.237 <<'EOF'
            cd ~/apps/ApiJO_Back
            git checkout main
            git pull origin main
            git pull origin main
          EOF

      - name: etape 4 Gestion Docker
        run: |
          ssh -o StrictHostKeyChecking=no deploy@167.172.53.237 <<'EOF'
            docker stop apijo || true
            docker rm apijo || true
            cd ~/apps/ApiJO_Back
            docker build --no-cache -t apijo .
            docker run -d --name apijo -p 8000:8000 apijo
          EOF