name: Deploiement API en Production

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tester l'application
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: 'testuser'
          POSTGRES_PASSWORD: 'testpass'
          POSTGRES_DB: 'testdb'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_NAME: "testdb"
      DATABASE_USER: "testuser"
      DATABASE_PASSWORD: "testpass"
      DATABASE_HOST: "localhost"
      DATABASE_PORT: "5432"
      DEBUG: "True"
      ALLOWED_HOSTS: "127.0.0.1,localhost"
      CORS_ALLOWED_ORIGINS: "http://localhost,http://127.0.0.1"
    steps:
      - uses: actions/checkout@v3
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          python manage.py test -v 2

  deploy:
      needs: test
      if: success()
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Deploy to server via SSH
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              set -e
              cd /home/deploy/apps/ApiJO_Back
              git fetch origin main
              git reset --hard origin/main
              source .venv/bin/activate
              pip install -r requirements.txt
              python manage.py makemigrations --noinput
              python manage.py migrate --noinput
              sudo systemctl restart gunicorn_api
