name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd ~/apps/ApiJO_Back
          git pull origin main
          source .venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          sudo systemctl restart gunicorn_api
